### ISSUE TITLE
metadata can get too big for server to handle

### ISSUE THREAD

**Issue by MCLV-pandorabox** [pandorabox-io/banners#5]
A player on our server recently found out that button mashing the overlays can cause metadata to become so large that serializeString16 (in /src/server.cpp:8) can not handle it and crashes the server when a banner is placed or dug.

Tested with banners:banner_wood
Tested 100 overlays. Didn't reproduce the error.

fix: should probably limit the amount of texture modifiers to something more reasonable than infinite

The Offending flag has been captured :rofl: (see attached [offending_flag.txt](https://github.com/user-attachments/files/17932874/offending_flag.txt))

Special thanks to ripyee on pandorabox.io

**Comment by SwissalpS** [comment]
Previously has happened, it's just so rare that players actually trigger this bug, that we hadn't bothered to fix it.

Of course you are correct, and thanks for opening the issue.

**Comment by SwissalpS** [comment]
The relevant commits are:
https://github.com/pandorabox-io/banners/pull/6/commits/78be1611c3d3113fb7d4d6e6e19b0d54ace7cb31
https://github.com/pandorabox-io/banners/pull/6/commits/3d22f9b76bff4eae7c1cacf47de833f126117722

**Comment by SwissalpS** [comment]
I have some more ideas to limit the resulting metadata further, that's why the PR is still in draft. Feel free to start testing though.
